Rebranding pass plus refactor
Azure-Samples/ms-identity-docs-code-dotnet pull request #49
Opened 2023-10-16 14:00 UTC by OwenRichards1

## Purpose
Remove references to Azure AD + 
* ...

## Does this introduce a breaking change?

```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[X] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

* Test the code
```
Verify changes are correct
```

2023-10-19 14:49 UTC, cilwerner requested changes
Good start, just looking through and see that there's a lot of `Admin center`, or `Entra ID`, we need to be consistent with the rebranding -> `Microsoft Entra admin center`, and use https://learn.microsoft.com/en-us/azure/active-directory/fundamentals/new-name for reference.

Won't do a full depth review for the moment until you've done another pass

2023-10-19 14:59 UTC, cilwerner commented on web-app-aspnet/appsettings.json
> +    "TenantId": "Enter_the_Application_Id_Here",
Wrong way round

2023-10-26 14:38 UTC, henrymbuguakiarie commented on console-cli/Program.cs
>      TenantId = "",
```suggestion
    TenantId = "Enter_the_Tenant_ID_Here",

```

2023-10-26 14:38 UTC, henrymbuguakiarie commented on console-cli/Program.cs
>      ClientId = ""
```suggestion
    ClientId = "Enter_the_Application_Id_Here"

```

2023-10-26 14:38 UTC, henrymbuguakiarie commented on console-cli/README.md
>  TenantId = "",
```suggestion
TenantId = "Enter_the_Tenant_ID_Here",
```

2023-10-26 14:38 UTC, henrymbuguakiarie commented on console-cli/README.md
>  ClientId = ""
```suggestion
ClientId = "Enter_the_Application_Id_Here"
```

2023-10-26 14:38 UTC, henrymbuguakiarie commented on console-daemon/Program.cs
>      Authority = "",
```suggestion
    Authority = "https://login.microsoftonline.com/Enter_the_Tenant_ID_Here",

```

2023-10-26 14:38 UTC, henrymbuguakiarie commented on console-daemon/Program.cs
>      ClientSecret = "",
```suggestion
    ClientSecret = "Enter_the_Client_Secrect_Here",

```

2023-10-26 14:38 UTC, henrymbuguakiarie commented on console-daemon/Program.cs
>      ClientId = "",
```suggestion
    ClientId = "Enter_the_Application_Id_Here",

```

2023-10-26 14:38 UTC, henrymbuguakiarie commented on console-daemon/Program.cs
>      ClientObjectId = ""
```suggestion
    ClientObjectId = "Enter_the_Object_ID_Here"

```

2023-10-26 14:40 UTC, cilwerner requested changes
A lot needed here, but also there may be things that I can't see

2023-10-26 14:40 UTC, cilwerner commented on console-cli/Program.cs
> +    // 'Directory (tenant) ID' of app registration in the Admin center - this value is a GUID
```suggestion
    // 'Directory (tenant) ID' of app registration in the Microsoft Entra admin center - this value is a GUID

```
BULK edit

2023-10-26 14:40 UTC, cilwerner commented on console-cli/Program.cs
> +    // 'Application (client) ID' of app registration in Admin center - this value is a GUID
```suggestion
    // 'Application (client) ID' of app registration in Microsost Entra admin center - this value is a GUID

```

2023-10-26 14:40 UTC, cilwerner commented on console-cli/Program.cs
>      TenantId = "",
```suggestion
    TenantId = "Enter_the_Tenant_ID_Here",

```
BULK edit

2023-10-26 14:40 UTC, cilwerner commented on console-cli/Program.cs
>      ClientId = ""
```suggestion
    ClientId = "Enter_the_Application_ID_URI_Here"

```

2023-10-26 14:40 UTC, cilwerner commented on console-daemon/Program.cs
>      Authority = "",
```suggestion
    Authority = "https://login.microsoftonline.com/Enter_the_Tenant_ID_Here",

```
BULK

2023-10-26 14:40 UTC, cilwerner commented on console-daemon/Program.cs
>      ClientSecret = "",
```suggestion
    ClientSecret = "Enter_the_Client_Secret_Value_Here",

```
BULK

2023-10-26 14:40 UTC, cilwerner commented on console-daemon/Program.cs
>      ClientObjectId = ""
```suggestion
    ClientObjectId = "Enter_the_Client_Object_ID_Here"

```

BULK

2023-10-26 14:40 UTC, cilwerner commented on console-daemon/README.md
Microsoft Entra admin center spot on here, just add the Enter_XXX_Here for the strings.

2023-10-26 14:40 UTC, cilwerner commented on desktop-winui/MainWindow.xaml.cs
> +                     // 'Tenant ID' of your Entra ID instance - this value is a GUID
```suggestion
                     // 'Tenant ID' of your Microsoft Entra instance - this value is a GUID

```
BULK

2023-10-26 14:40 UTC, cilwerner commented on desktop-winui/README.md
> +> :information_source: **Bold text** in the tables above matches (or is similar to) a UI element in the Microsoft Admin center, while `code formatting` indicates a value you enter into a text box in
```suggestion
> :information_source: **Bold text** in the tables above matches (or is similar to) a UI element in the Microsoft Entra admin center, while `code formatting` indicates a value you enter into a text box in the Microsoft Entra admin center.

```

2023-10-26 14:40 UTC, cilwerner commented on desktop-winui/README.md
> +// 'Tenant ID' of your Entra AD instance - this value is a GUID
```suggestion
// 'Tenant ID' of your Microsoft Entra instance - this value is a GUID

```

2023-10-26 14:40 UTC, cilwerner commented on console-cli/README.md
Make changes in the Program.cs and you can then directly copy them over to this, as its a snippet

2023-10-26 14:40 UTC, cilwerner commented on console-daemon/Program.cs
Bulk change `ClientID = ""` to add the Enter_Application_ID_Here (can't remember top of mind.)

2023-10-26 14:40 UTC, cilwerner commented on desktop-winforms/README.md
Microsoft Entra admin center

2023-10-26 14:40 UTC, cilwerner commented on desktop-wpf/MainWindow.xaml.cs
> +                    // 'Tenant ID' of your Entra ID instance - this value is a GUID
```suggestion
                    // 'Tenant ID' of your Microsoft Entra instance - this value is a GUID

```

2023-10-26 14:40 UTC, cilwerner commented on desktop-wpf/README.md
> +> :information_source: **Bold text** in the tables above matches (or is similar to) a UI element in the Microsoft Admin center, while `code formatting` indicates a value you enter into a text box in
```suggestion
> :information_source: **Bold text** in the tables above matches (or is similar to) a UI element in the Microsoft Entra admin center, while `code formatting` indicates a value you enter into a text box in the Microsoft Entra admin center.
```

2023-10-26 14:40 UTC, cilwerner commented on desktop-wpf/README.md
> +// 'Tenant ID' of your Entra ID instance - this value is a GUID
```suggestion
// 'Tenant ID' of your Microsoft Entra instance - this value is a GUID
```

2023-10-26 14:40 UTC, cilwerner commented on web-app-aspnet/README.md
> +    "ClientSecret": "[Copy the client secret added to the app from the admin center]",
```suggestion
    "TenantId": "Enter_'common'_or_'organizations'_the_Tenant_ID_Here",
    "ClientId": "Enter_the_Application_Id_Here",
    "ClientSecret": "Enter_the_Client_Secret_Value_Here",
```
Ok here is an outlier... are there others like this?

2024-01-16 15:26 UTC, closed without merging