update-spa-to.net8
Azure-Samples/ms-identity-docs-code-dotnet pull request #66
Opened 2024-02-09 18:10 UTC by OwenRichards1

## Purpose
Update spa-blazor-wasm to .NET 8

Also cleared ongoing error of:

`ms-identity-docs-code-dotnet\spa-blazor-wasm\Microsoft.NET.Sdk.Razor.SourceGenerators\Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator\Shared_LoginDisplay_razor.g.cs(146,75): war
ning CS0618: 'SignOutSessionStateManager' is obsolete: 'Use 'Microsoft.AspNetCore.Components.Webassembly.Authentication.NavigationManagerExtensions.NavigateToLogout' instead.' [C:\Repos\identity_repo\ms-identity-docs-code-samples\ms-identity-do
cs-code-dotnet\spa-blazor-wasm\BlazorWasm.csproj]`
* ...

## Does this introduce a breaking change?

```
[X] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?
```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
cd ms-identity-docs-code-dotnet\spa-blazor-wasm
dotnet run
```

* Test the code

1. Verify sign-in occurs correctly
2. Ensure updates to `Microsoft.AspNetCore.Components.WebAssembly.DevServer` are best practice

```

## What to Check

1.  Verify all updates are correct

1. Please verify the update of  `Microsoft.AspNetCore.Components.WebAssembly.DevServer`

**Note:**  Version 6.0.0 presented both a `http` & `https` localhost.

Upgrading to version 8.0 only presents a `http` localhost.

Please verify which should version is best to merge to the sample
* ...

2024-02-09 18:28 UTC, jennyf19 approved these changes
LGTM, did not pull the code and try, but the changes look correct.
:shipit:

2024-02-09 19:11 UTC, localden requested changes

2024-02-09 19:11 UTC, localden commented on spa-blazor-wasm/README.md
> +The standalone app in this scenario has been created using the ASP.NET Core 8.0 Blazor WebAssembly template, and slightly modified allow sign-in with a Microsoft Entra ID account. The app uses the [M
Since this is _not_ the vanilla MSAL (Microsoft.Identity.Client), we probably need to clarify this somehow.

2024-02-09 19:11 UTC, localden commented on spa-blazor-wasm/README.md
> +   :link: For more information, please take a look [.NET WebAssembly build tools](https://docs.microsoft.com/en-us/aspnet/core/blazor/tooling?view=aspnetcore-8.0&pivots=linux#net-webassembly-build-to
```suggestion
   :link: For more information, please take a look [.NET WebAssembly build tools](https://learn.microsoft.com/aspnet/core/blazor/tooling?view=aspnetcore-8.0&pivots=linux#net-webassembly-build-tools)
```

2024-02-09 19:11 UTC, localden commented on spa-blazor-wasm/README.md
> +1. Select Logout to sign-out, you can now close the browser.
```suggestion
1. Select Logout to sign-out. Once signed out, you can close the browser.
```

2024-02-12 15:33 UTC, OwenRichards1 commented
Thank you @jennyf19 & @localden!

2024-02-12 15:34 UTC, merged